### ISSUE TITLE
Error: Cannot find module 'call-of-duty-api'

### ISSUE THREAD

**Issue by MattMcNeill** [Lierrmm/Node-CallOfDuty#11]
I placed your sample code into an app.js. I am getting the following error.  Any ideas?  

module.js:549
    throw err;
    ^

Error: Cannot find module 'call-of-duty-api'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/ubuntu/Node-CallOfDuty/app.js:2:13)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

**Comment by MattMcNeill** [comment]
Node v8.10.0
Ubuntu 18.04 server

**Comment by Lierrmm** [comment]
Have you installed the npm module with `npm i call-of-duty-api`?

**Comment by MattMcNeill** [comment]
That worked. Thanks.  And thanks for your work on this!
