### ISSUE TITLE
Cannot read property 'status' of undefined

### ISSUE THREAD

**Issue by vandevelde-jacob** [Lierrmm/Node-CallOfDuty#48]
I've observed instances of the below:

During the reject of API promises the error handling function is being passed in a value of undefined and throws an `UnhandledPromiseRejectionWarning`.

```
reject(this.apiErrorHandling(error.response)); // error.response === undefined

109 ...
110 apiErrorHandling(response) {
111        switch (response.status) { // response is undefined and throws the exception below.
112            case 200:
113 ...
```

Stacktrace:
```
(node:14926) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'status' of undefined
    at helpers.apiErrorHandling (/repo/node_modules/call-of-duty-api/index.js:111:26)
    at /repo/node_modules/call-of-duty-api/index.js:74:29
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:14926) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
```

**Comment by Lierrmm** [comment]
Do you have the exact request you were making when this happened?

**Comment by vandevelde-jacob** [comment]
Unfortunately not.
It was the endpoint to get MW warzone stat  and is a request I've made many times in the past
Just seems to be a once off that happens from time to time.

**Comment by thedevbc** [comment]
I made a pull request with a possible solution to this, #56
